// Lazy room loaders: metadata stays lightweight; each interactive room is parsed on demand.
export const ROOM_LOADERS = {
  teachable: () => import("./rooms/teachable.js").then((m) => m.roomTeachable),
  "neural-net": () => import("./rooms/neural-net.js").then((m) => m.roomNeuralNet),
  overfitting: () => import("./rooms/overfitting.js").then((m) => m.roomOverfitting),
  "decision-tree": () => import("./rooms/decision-tree.js").then((m) => m.roomDecisionTree),
  reinforcement: () => import("./rooms/reinforcement.js").then((m) => m.roomReinforcement),
  clustering: () => import("./rooms/clustering.js").then((m) => m.roomClustering),
  tokenizer: () => import("./rooms/tokenizer.js").then((m) => m.roomTokenizer),
  embeddings: () => import("./rooms/embeddings.js").then((m) => m.roomEmbeddings),
  attention: () => import("./rooms/attention.js").then((m) => m.roomAttention),
  "next-token": () => import("./rooms/next-token.js").then((m) => m.roomNextToken),
  diffusion: () => import("./rooms/diffusion.js").then((m) => m.roomDiffusion),
  recommendation: () => import("./rooms/recommendation.js").then((m) => m.roomRecommendation),
  bias: () => import("./rooms/bias.js").then((m) => m.roomBias),
  adversarial: () => import("./rooms/adversarial.js").then((m) => m.roomAdversarial),
  turing: () => import("./rooms/turing.js").then((m) => m.roomTuring),
  chatbot: () => import("./rooms/chatbot.js").then((m) => m.roomChatbot),
  rag: () => import("./rooms/rag.js").then((m) => m.roomRag),
  finetune: () => import("./rooms/finetune.js").then((m) => m.roomFinetune),
  agents: () => import("./rooms/agents.js").then((m) => m.roomAgents),
  multimodal: () => import("./rooms/multimodal.js").then((m) => m.roomMultimodal),
  "context-window": () => import("./rooms/context-window.js").then((m) => m.roomContextWindow),
  "prompt-injection": () => import("./rooms/prompt-injection.js").then((m) => m.roomPromptInjection),
  rlhf: () => import("./rooms/rlhf.js").then((m) => m.roomRlhf),
  energy: () => import("./rooms/energy.js").then((m) => m.roomEnergy),
  reasoning: () => import("./rooms/reasoning.js").then((m) => m.roomReasoning),
  summary: () => import("./rooms/summary.js").then((m) => m.roomSummary),
};